### ISSUE TITLE
Deprecated core-js@2.6.11

### ISSUE THREAD

**Issue by asbjornu** [jgillick/jira-changelog#10]
When installing `jira-changelog` I get the following warning:

>npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
>+ jira-changelog@1.5.0

Would it be possible to upgrade to `core-js@3` to resolve this warning?

**Comment by jgillick** [comment]
The project doesn't import core-js directly. I believe it's included as part of @babel/polyfill, so an upgrade of that library might get rid of the warning.

**Comment by jgillick** [comment]
What version of node are you running on? I do not see this warning when I run `jira-changelog`

**Comment by jgillick** [comment]
I've started a new branch with some package upgrades, including `core-js`. I want to add some unit tests before merging it into master, but give it a try and see if it works for you: 
https://github.com/jgillick/jira-changelog/tree/core-js-upgrade

```bash
git pull
git checkout core-js-upgrade
npm run clean
npm run build
npm install -g .

...

jira-changelog -V 
# Should output 1.5.2
```

**Comment by jgillick** [comment]
If you're interested, as part of adding unit tests, I cleaned up a lot of code and made some upgrades to remove some of the changelog noise. I've released this version as `1.6.0-beta.0`, if you want to try it. See the changes here: https://github.com/jgillick/jira-changelog/pull/13

I plan to release this fully in a few weeks.

**Comment by asbjornu** [comment]
`npm i -S jira-changelog@1.6.0-beta.0` works like a charm. Thanks!

**Comment by jgillick** [comment]
FYI, I discovered a bug in this version which breaks the slack integration. If you use this, update to beta-1: `jira-changelog@1.6.0-beta.1`

**Comment by jgillick** [comment]
Production version 1.6.0 released!
