### ISSUE TITLE
Question~ What part of this makes the Jira Issue.key in square brackets a clickable link?

### ISSUE THREAD

**Issue by Kimba666** [jgillick/jira-changelog#17]
Situation:  I've already got a changelog generating automatically, I want to keep the current structure that I've already got.  HOWEVER, I am trying to find a way to add the Jira Issue.Keys in square brackets in the commit messages to become clickable links on the changelog. 

Example~  git commit -m 'fix: did the thing [JIRA-123]'

would populate on the changelog under "Bug Fixes" (current functionality) but the Issue.key in brackets is now a hyperlink that will take the user to the referenced jira task.

**Comment by jgillick** [comment]
This would be done in your `changelog.config.js` file. How you do it depends on where this changelog is being used. Look at the `template` property in `changelog.config.js`, this is where the output is generated. 

⚠️ **NOTE: The slack recommendations are dependent on the new version published today: 1.6.3**

To simply use an HTML link, you would wrap the key in an anchor tag:

```
...
[<a href="<%= jira.baseUrl + '/browse/' + ticket.key %>"><%= ticket.key %></a>]
...
```

If the changelog is sent directly to slack, you can use slack's [link format](https://api.slack.com/reference/surfaces/formatting#linking-urls):
```
...
[<<%= jira.baseUrl + '/browse/' + ticket.key %>|<%= ticket.key %>>]
...
```

Alternatively, you could support both by using the `transformForSlack` property. Start by defining the links as HTML and then convert them to slack links when the changelog is sent to slack.

For example, not tested:

```js
transformForSlack: (content) => {
  return content.replace(/<a href="(.*?)">(.*?)<\/a>/, "<$1|$2>")
}
```

_The above example should have error handling and more intelligent logic to prevent unexpected errors._

Let me know if that helps.

**Comment by jgillick** [comment]
Just reading through your question again, if you're talking about linking part of the git commit message (the part in the square brackets), then that's a different solution. In that case, you would use the `transformData` function in `changelog.config.js`.

This function is used to define any custom transformations on the changelog data before it is sent to the template.

The `data` property sent to that function is generated by [transformCommitLogs](https://github.com/jgillick/jira-changelog/blob/master/src/template.js#L167) and looks like this:
```
{
  commits: {
    all: [],       // all commits
    tickets: [],   // commits associated with jira tickets
    noTickets: [], // commits not associated with jira tickets
  },
  tickets: {
    all: [],       // all tickets
    approved: [],  // tickets marked as approved
    pending: [],   // tickets not marked as approved
    pendingByOwner: [], // pending tickets arranged under ticket reporters.
  }
}
```

To see what this object looks like for your changelog:

```javascript
transformData: function(data){ 
  console.log(JSON.stringify(data, null, '  ')); 
  return data;
}
```

So, for example, transforming all commit messages would look something like this (not tested):

```javascript
transformData: (data) => {
  // Link the ticket numbers in all commit summaries.
  data.commits.all.forEach((commit) => {
    commit.summary = commit.summary.replace(
      /\[([A-Z]+\-[0-9]+)\]/,
      '[<a href="https://YOU.atlassian.net/browse/$1">$1</a>]'
    );
  });
  return Promise.resolve(data);
},
```

**Comment by Kimba666** [comment]
Thank you very much good sir, you are indeed a wizard. 🥇
