### ISSUE TITLE
git commit range not resepcted - pull all issues and takes forever

### ISSUE THREAD

**Issue by clehene** [jgillick/jira-changelog#19]
`jira-changelog --range e9f569df..e9f569df` - should do nothing as it's an empty range but pulls all isues
`jira-changelog --range e9f569df~1..e9f569df` - should do exactly one, pulls everything
`jira-changelog --range  e9f569df..cd1f7cd6` - again pulls everything 

Each of these take about 2 minutes and then dump the whole jira.

Am I doing something wrong?

**Comment by t-beckmann** [comment]
I've had the same issue and found the tool parses triple-dot ranges only. This is because of https://github.com/jgillick/jira-changelog/blob/v1%2C6.3/src/cli.js#L144 and is against what is documented in the readme file. Try `jira-changelog --range e9f569df...cd1f7cd6`.

**Comment by jgillick** [comment]
Thank you for reporting this. The range parsing should not be fixed in version v2.0.0 (fix commit: https://github.com/jgillick/jira-changelog/commit/22dfbdbee35cfb5f955a6f7d764616c4ae6f3941). Please let me know if this works for you.
