### ISSUE TITLE
Range parsing doesn't support tags with dot anymore

### ISSUE THREAD

**Issue by pasdam** [jgillick/jira-changelog#27]
Range parsing is broken when using tags with dots, it used to work just fine with `v1.6.3`, but it gives the following with `v2.1.0`:

```sh
$ jira-changelog --range v0.1.27...v0.1.32
fatal: ambiguous argument 'v0...1.27...v0.1.32': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

fatal: ambiguous argument 'v0...1.27...v0.1.32': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

I believe it has to do with this commit: https://github.com/jgillick/jira-changelog/commit/22dfbdbee35cfb5f955a6f7d764616c4ae6f3941#diff-a3751a8ca1ab5bdf5d4bb6b4c3861d9a81205bc01b080e57301090b6e8b34165

**Comment by mrmeyers99** [comment]
I just ran into this issue today too.

**Comment by jgillick** [comment]
This has been resolved with https://github.com/jgillick/jira-changelog/pull/28 and deployed to version 2.2.0
